movieRecommender/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^recommender/', include('recommender.urls')),
    url(r'^admin/', admin.site.urls),
]

recommender/urls.py
from django.conf.urls import url
from . import views

app_name = 'recommender'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/', views.UserFormView.as_view(), name='register'),
    url(r'^login/', views.UserLogin.as_view(), name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^user/search/', views.user_search, name='user_search'),
    url(r'^search/', views.search, name='search'),
    url(r'^user/(?P<movie_id>[0-9]+)/', views.user_movie_details, name='user_movie_detail'),
    url(r'^(?P<movie_id>[0-9]+)/', views.movie_details, name='movie_detail'),
    url(r'^user/', views.user, name='user'),
    url(r'^rating/', views.rating, name='rating')
]

recommender/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.


class Movie(models.Model):
    id = models.IntegerField(primary_key=True)
    adult = models.BooleanField(default=False)
    title = models.TextField(max_length=100, null=True, blank=True)
    overview = models.TextField(max_length=500, null=True, blank=True)
    popularity = models.FloatField(default=0.0, null=True, blank=True)
    poster_path = models.TextField(max_length=50, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    genre_ids = models.TextField(max_length=100, null=True, blank=True)
    average_rating = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Rating(models.Model):
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return str(self.rating)


class Genre(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.genre

recommender/forms.py
from django.contrib.auth.models import User
from django import forms


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)

recommender/views.py
# -*- coding:
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import UserRegisterForm, UserLoginForm
from django.views.generic import View
from .models import Movie, UserInfo, Rating, Genre
import numpy as np
from recommender.kmean_cf import item_similarity, predict_rating_item, similarity, predict_rating_user
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    movies = Movie.objects.all()

    return render(request, 'recommender/index.html', {'movies': movies})


@login_required
def user(request):
    user = request.user.userinfo_set.all()[0]
    movies = Movie.objects.all()
    users = UserInfo.objects.all()
    ratings = np.zeros((len(users), len(movies)))

    for rating in Rating.objects.all():
        ratings[rating.user.id - 1, rating.movie.id - 1] = rating.rating

    sim = similarity(ratings)

    pred = predict_rating_user(ratings, sim)
    indices = np.argsort(pred[user.id - 1, :])[:-11:-1] + 1

    recommended_movies = [Movie.objects.get(id=i) for i in indices]
    popular_movies = Movie.objects.order_by('-popularity')[:10]
    latest_movies = Movie.objects.order_by('-release_date')[:10]
    context = {
        'recommended_movies': recommended_movies,
        'popular_movies': popular_movies,
        'latest_movies': latest_movies
    }
    return render(request, 'recommender/user.html', context)


def rating(request):
    movie = Movie.objects.get(id=request.GET['movie_id'])
    user = request.user.userinfo_set.all()[0]
    try:
        Rating.objects.get(movie=movie, user=user).delete()
    except Rating.DoesNotExist:
        pass
    rating = Rating(user=user, movie=movie, rating=request.GET['rating'])
    rating.save()
    return HttpResponse("rating modified")


@login_required
def user_movie_details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    genres = Genre.objects.filter(movie=movie)
    movies = Movie.objects.all()
    users = UserInfo.objects.all()
    user = request.user
    user = user.userinfo_set.all()[0]
    try:
        user_rating = Rating.objects.get(movie=movie, user=user)
    except:
        user_rating = 0
    ratings = np.zeros((len(users), len(movies)))

    for rating in Rating.objects.all():
        ratings[rating.user.id - 1, rating.movie.id - 1] = rating.rating

    item_sim = item_similarity(ratings)
    count = np.sum(item_sim == 1)
    np.place(item_sim, item_sim == 1, np.zeros(count))

    indices = np.argsort(item_sim[int(movie_id) - 1, :])[:-12:-1] + 1
    recommended_movies = [Movie.objects.get(id=i) for i in indices if i != movie.id][:10]

    context = {
        'movie': movie,
        'recommended_movies': recommended_movies,
        'genres': genres,
        'rating': user_rating
    }

    return render(request, 'recommender/user_movie_details.html', context=context)


def movie_details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    genres = Genre.objects.filter(movie=movie)
    movies = Movie.objects.all()
    users = UserInfo.objects.all()
    ratings = np.zeros((len(users), len(movies)))

    for rating in Rating.objects.all():
        ratings[rating.user.id - 1, rating.movie.id - 1] = rating.rating

    item_sim = item_similarity(ratings)
    count = np.sum(item_sim == 1)
    np.place(item_sim, item_sim == 1, np.zeros(count))
    indices = np.argsort(item_sim[int(movie_id) - 1, :])[:-7:-1] + 1
    recommended_movies = [Movie.objects.get(id=i) for i in indices if i != movie.id][:5]

    context = {
        'movie': movie,
        'recommended_movies': recommended_movies,
        'genres': genres
    }

    return render(request, 'recommender/movie_details.html', context=context)


def user_details(request, user_id):
    user = UserInfo.objects.get(user_id)
    movies = Movie.objects.all()
    users = UserInfo.objects.all()
    ratings = np.zeros((len(users), len(movies)))
    for i in range(len(users)):
        for j in range(len(movies)):
            ratings[i, j] = Rating.objects.get(user=users[i], movie=movies[j]).rating


def user_logout(request):
    logout(request)
    return redirect('recommender:index')


class UserFormView(View):
    form_class = UserRegisterForm
    template_name = 'recommender/user_registration.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            userinfo = UserInfo.objects.create(user=user)
            userinfo.id = UserInfo.objects.count() + 1

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('recommender:user')

        return render(request, self.template_name, {'form': form})


class UserLogin(View):
    form_class = UserLoginForm
    template_name = 'recommender/user_login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('recommender:user')

        return render(request, self.template_name, {'form': form})


def search(request):
    query_string = request.POST['search']
    try:
        movies = Movie.objects.filter(title__icontains=query_string)
    except Movie.DoesNotExist:
        movies = []
    return render(request, 'recommender/search.html', {'movies': movies})


def user_search(request):
    query_string = request.POST['search']
    try:
        movies = Movie.objects.filter(title__icontains=query_string)
    except Movie.DoesNotExist:
        movies = []
    return render(request, 'recommender/user_search.html', {'movies': movies})

recommender/templates/recommender/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    {% load staticfiles %}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'recommender:index' %}"><span class = "glyphicon glyphicon-film"></span>&nbsp;Movies</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'recommender:register' %}"><span class = "glyphicon glyphicon-user"></span>&nbsp;Sign Up</a> </li>
                <li><a href="{% url 'recommender:login' %}"><span class = "glyphicon glyphicon-log-in"></span>&nbsp;Login</a></li>
            </ul>
            <form class="navbar-form" action="{% url 'recommender:search' %}" method="post">
                {% csrf_token %}
              <div class="input-group col-xs-4">
                <input type="text" name="search" class="form-control" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
              </div>
            </form>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

recommender/templates/recommender/form_template.html
<div class="form-group col-sm-12">
    {% for field in form %}
        <div class="form-field-error col-sm-offset-4 col-sm-8 text-danger small">{{ field.errors }}</div>
        <div class="form-field-label col-sm-4">{{ field.label_tag }}</div>
        <div class="form-field col-sm-8">{{ field }}</div>
    {% endfor %}
</div>

recommender/templates/recommender/index.html
{%  extends 'recommender/base.html' %}
{% block body %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'recommender/styles/index.css' %}">
    <div class="col-sm-12 all-movies">
    {% for movie in movies %}
        <div class="col-sm-2 movie_gist">
            <div class="thumbnail">
                <a href="{% url 'recommender:movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
            </div>
            <div class="caption">
                <b>{{ movie.title }}</b>
                <h6>{{ movie.release_date }}</h6>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

recommender/templates/recommender/movie_details.html
{%  extends 'recommender/base.html' %}
{% block body %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'recommender/styles/movie_details.css' %}">
    <div class="movie_details col-sm-12">
        <div class="col-sm-2 movie_gist">
            <div class="thumbnail">
                <a href="{% url 'recommender:movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
            </div>
            <div class="caption">
                <h4><b>{{ movie.title }}</b></h4>
                <h6>{{ movie.release_date }}</h6>
            </div>
        </div>
        <div class="movie_description col-sm-9">
            <div class="movie_row col-sm-12">
                <div class="movie_label col-sm-2"><b>Title</b></div>
                <div class="col-sm-10">{{ movie.title }}</div>
            </div>
            <div class="movie_row col-sm-12">
                <div class="movie_label col-sm-2"><b>Overview</b></div>
                <div class="overview_value col-sm-10">{{ movie.overview }}</div>
            </div>
            <div class="genre_row movie_row col-sm-12">
                <div class="movie_label col-sm-2"><b>Genre</b></div>
                <div class="col-sm-10">
                    {% if not genres %}
                        <div class="genre">Unknown</div>
                    {% endif %}
                    {% for genre in genres %}
                        <div class="genre">{{ genre.genre }}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>


    <div class="col-sm-12 recommendation">
    <div class="fluid-container related-movies"><h3>&nbsp;Related Movies</h3><hr></div>
    {% for movie in recommended_movies %}
        <div class="col-sm-2 movie_gist">
            <div class="thumbnail">
                <a href="{% url 'recommender:movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
            </div>
            <div class="caption">
                <h4><b>{{ movie.title }}</b></h4>
                <h6>{{ movie.release_date }}</h6>
            </div>
        </div>
    {% endfor %}
    </div>
{%  endblock %}

recommender/templates/recommender/search.html
{%  extends 'recommender/base.html' %}
{% block body %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'recommender/styles/index.css' %}">
    <div class="col-sm-12 all-movies">
    {% if not movies %}
        <h1 class="error_message">Search did not match any movie...</h1>
    {% else %}
        {% for movie in movies %}
            <div class="col-sm-2 movie_gist">
                <div class="thumbnail">
                    <a href="{% url 'recommender:movie_detail' movie.id %}"><img src="{% static 'recommender/images' %}{{ movie.poster_path }}"></a>
                </div>
                <div class="caption">
                    <b>{{ movie.title }}</b>
                    <h6>{{ movie.release_date }}</h6>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    </div>
{% endblock %}

recommender/templates/recommender/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'recommender/styles/user.css' %}">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'recommender:user' %}"><span class = "glyphicon glyphicon-film"></span>&nbsp;Movies</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'recommender:logout' %}"><span class = "glyphicon glyphicon-log-out"></span>&nbsp;Logout</a></li>
            </ul>
            <form class="navbar-form" action="{% url 'recommender:user_search' %}" method="post">
                {% csrf_token %}
              <div class="input-group col-xs-4">
                <input type="text" name="search" class="form-control" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
              </div>
            </form>
        </div>
    </nav>
    <div class="col-sm-12 recommendation">
    <div class="fluid-container related-movies"><h3>&nbsp;Recommended Movies</h3><hr></div>
    {% for movie in recommended_movies %}
        <div class="col-sm-2 movie_gist">
            <div class="thumbnail">
                <a href="{% url 'recommender:user_movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
            </div>
            <div class="caption">
                <h4><b>{{ movie.title }}</b></h4>
                <h6>{{ movie.release_date }}</h6>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="col-sm-12 recommendation">
        <div class="fluid-container related-movies"><h3>&nbsp;Popular Movies</h3><hr></div>
        {% for movie in popular_movies %}
            <div class="col-sm-2 movie_gist">
                <div class="thumbnail">
                    <a href="{% url 'recommender:user_movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
                </div>
                <div class="caption">
                    <h4><b>{{ movie.title }}</b></h4>
                    <h6>{{ movie.release_date }}</h6>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-sm-12 recommendation">
        <div class="fluid-container related-movies"><h3>&nbsp;Latest Movies</h3><hr></div>
        {% for movie in latest_movies %}
            <div class="col-sm-2 movie_gist">
                <div class="thumbnail">
                    <a href="{% url 'recommender:user_movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
                </div>
                <div class="caption">
                    <h4><b>{{ movie.title }}</b></h4>
                    <h6>{{ movie.release_date }}</h6>
                </div>
            </div>
        {% endfor %}
    </div>
</body>
</html>

recommender/templates/recommender/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'recommender/styles/form.css' %}">
</head>
<body>
    <div class="fluid-container">
        <div class="form-container col-sm-offset-4 col-sm-4">
            <div class="form-register col-sm-12"><h3>Login</h3></div>
            <form action="" method="post">
                {% csrf_token %}
                    {%  include 'recommender/form_template.html' %}
            <div class="form-submit col-sm-offset-4">
                <button type="submit" class="btn btn-success">Login</button>
            </div>
            </form>
        </div>
    </div>
</body>
</html>

recommender/templates/recommender/user_movie_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        function rating() {
            var rating = {{ rating }}
            if (rating > 0) {
                $("#star" + rating).addClass("glyphicon-star");
                $("#star" + rating).prevAll().addClass("glyphicon-star");
                $("#star" + rating).nextAll().addClass("glyphicon-star-empty");
            }
            else {
                $("#star1").addClass("glyphicon-star-empty");
                $("#star1").nextAll().addClass("glyphicon-star-empty");
            }
        }
    </script>
</head>
<body onload="rating()">
    <link rel="stylesheet" href="{% static 'recommender/styles/movie_details.css' %}">
{#    <link rel="stylesheet" href="{% static 'recommender/styles/user.css' %}">#}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'recommender:user' %}"><span class = "glyphicon glyphicon-film"></span>&nbsp;Movies</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'recommender:logout' %}"><span class = "glyphicon glyphicon-log-out"></span>&nbsp;Logout</a></li>
            </ul>
            <form class="navbar-form" action="{% url 'recommender:user_search' %}" method="post">
                {% csrf_token %}
              <div class="input-group col-xs-4">
                <input type="text" name="search" class="form-control" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
              </div>
            </form>
        </div>
    </nav>

    <div class="movie_details col-sm-12">
        <div class="col-sm-2 movie_gist">
            <div class="thumbnail">
                <a href="{% url 'recommender:user_movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
            </div>
            <div class="caption">
                <h4><b>{{ movie.title }}</b></h4>
                <h6>{{ movie.release_date }}</h6>
            </div>
        </div>
        <div class="movie_description col-sm-9">
            <div class="movie_row col-sm-12">
                <div class="movie_label col-sm-2"><b>Title</b></div>
                <div class="col-sm-10">{{ movie.title }}</div>
            </div>
            <div class="movie_row col-sm-12">
                <div class="movie_label col-sm-2"><b>Overview</b></div>
                <div class="overview_value col-sm-10">{{ movie.overview }}</div>
            </div>
            <div class="genre_row movie_row col-sm-12">
                <div class="movie_label col-sm-2"><b>Genre</b></div>
                <div class="col-sm-10">
                    {% if not genres %}
                        <div class="genre col-sm-2">Unknown</div>
                    {% endif %}
                    {% for genre in genres %}
                        <div class="genre col-sm-2">{{ genre.genre }}</div>
                    {% endfor %}
                </div>
            </div>
            <div class="movie_row col-sm-12">
                <div class="movie_label col-sm-2"><b>Rating</b></div>
                <div class="col-sm-10">
                    <div id="star1" class="glyphicon"></div>
                    <div id="star2" class="glyphicon"></div>
                    <div id="star3" class=" glyphicon"></div>
                    <div id="star4" class=" glyphicon"></div>
                    <div id="star5" class=" glyphicon"></div>
                </div>
            </div>
        </div>
    </div>


    <div class="col-sm-12 recommendation">
    <div class="fluid-container related-movies"><h3>&nbsp;Related Movies</h3><hr></div>
    {% for movie in recommended_movies %}
        <div class="col-sm-2 movie_gist">
            <div class="thumbnail">
                <a href="{% url 'recommender:user_movie_detail' movie.id %}"><img src="{% static "recommender/images"%}{{ movie.poster_path }}"></a>
            </div>
            <div class="caption">
                <h4><b>{{ movie.title }}</b></h4>
                <h6>{{ movie.release_date }}</h6>
            </div>
        </div>
    {% endfor %}
    </div>
    <script>
        $('#star1').click(function(){
            $(this).parent().children().removeClass('glyphicon glyphicon-star glyphicon-star-empty');
            $(this).addClass('glyphicon glyphicon-star')
            $(this).prevAll().addClass('glyphicon glyphicon-star');
            $(this).nextAll().addClass('glyphicon glyphicon-star-empty');
            $.ajax({
                    url: "{% url 'recommender:rating' %}",
                    data: {
                        'movie_id': {{movie.id}},
                        'rating': 1
                    },
                    success: function(response){
                            window.alert("Rating Updated");
                    }
                }
            )
        });
        $('#star2').click(function(){
            $(this).parent().children().removeClass('glyphicon glyphicon-star glyphicon-star-empty');
            $(this).addClass('glyphicon glyphicon-star')
            $(this).prevAll().addClass('glyphicon glyphicon-star');
            $(this).nextAll().addClass('glyphicon glyphicon-star-empty');
            $.ajax({
                    url: "{% url 'recommender:rating' %}",
                    type: 'GET',
                    data: {
                        'movie_id': {{movie.id}},
                        'rating': 2
                    },
                    success: function(response){
                        window.alert("Rating Updated");
                    }
                }
            )
        });
        $('#star3').click(function(){
            $(this).parent().children().removeClass('glyphicon glyphicon-star glyphicon-star-empty');
            $(this).addClass('glyphicon glyphicon-star')
            $(this).prevAll().addClass('glyphicon glyphicon-star');
            $(this).nextAll().addClass('glyphicon glyphicon-star-empty');
            $.ajax({
                    url: "{% url 'recommender:rating' %}",
                    data: {
                        'movie_id': {{movie.id}},
                        'rating': 3
                    },
                    success: function(response){
                        window.alert("Rating Updated");
                    }
                }
            )
        });
        $('#star4').click(function(){
            $(this).parent().children().removeClass('glyphicon glyphicon-star glyphicon-star-empty');
            $(this).addClass('glyphicon glyphicon-star')
            $(this).prevAll().addClass('glyphicon glyphicon-star');
            $(this).nextAll().addClass('glyphicon glyphicon-star-empty');
            $.ajax({
                    url: "{% url 'recommender:rating' %}",
                    data: {
                        'movie_id': {{movie.id}},
                        'rating': 4
                    },
                    success: function(response){
                        window.alert("Rating Updated");
                    }
                }
            )
        });
        $('#star5').click(function(){
            $(this).parent().children().removeClass('glyphicon glyphicon-star glyphicon-star-empty');
            $(this).addClass('glyphicon glyphicon-star')
            $(this).prevAll().addClass('glyphicon glyphicon-star');
            $(this).nextAll().addClass('glyphicon glyphicon-star-empty');
            $.ajax({
                    url: "{% url 'recommender:rating' %}",
                    data: {
                        'movie_id': {{movie.id}},
                        'rating': 5
                    },
                    success: function(response){
                        window.alert("Rating Updated");
                    }
                }
            )
        });
    </script>
</body>
</html>

recommender/templates/recommender/user_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        function rating() {
            var rating = {{ rating }}
            if (rating > 0) {
                $("#star" + rating).addClass("glyphicon-star");
                $("#star" + rating).prevAll().addClass("glyphicon-star");
                $("#star" + rating).nextAll().addClass("glyphicon-star-empty");
            }
            else {
                $("#star1").addClass("glyphicon-star-empty");
                $("#star1").nextAll().addClass("glyphicon-star-empty");
            }
        }
    </script>
</head>
<body>
    {% load static %}
    <link rel="stylesheet" href="{% static 'recommender/styles/user.css' %}">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'recommender:user' %}"><span class = "glyphicon glyphicon-film"></span>&nbsp;Movies</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'recommender:logout' %}"><span class = "glyphicon glyphicon-log-out"></span>&nbsp;Logout</a></li>
            </ul>
            <form class="navbar-form ">
              <div class="input-group col-xs-4">
                <input type="text" class="form-control" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
              </div>
            </form>
        </div>
    </nav>
    <div class="col-sm-12 all-movies">
    {% if not movies %}
        <h1 class="error_message">Search did not match any movie...</h1>
    {% else %}
        {% for movie in movies %}
            <div class="col-sm-2 movie_gist">
                <div class="thumbnail">
                    <a href="{% url 'recommender:user_movie_detail' movie.id %}"><img src="{% static 'recommender/images' %}{{ movie.poster_path }}"></a>
                </div>
                <div class="caption">
                    <b>{{ movie.title }}</b>
                    <h6>{{ movie.release_date }}</h6>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    </div>

</body>
</html>